language: go

go: 
  - 1.8.x
  - 1.9.x
  - tip

install:
  - make install

script:
  - make lint
  - make test

notifications:
  email:
    recipients:
    - Travis.APA@a-bc.net
    on_success: always
    on_failure: always
